[package]
name = "proj1"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.148"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0"
assembly_macros = { path = "assembly_macros" }
